#!/usr/bin/env python

import os
import sys

from diffusers import StableDiffusionPipeline

os.makedirs("diffusers-cache", exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    "valhalla/emoji-diffusion",
    cache_dir="diffusers-cache",
    use_auth_token=sys.argv[1],
)
